title = "DreamHigher"
baseURL = "/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon.png"
  description = ""
  facebook = "https://www.facebook.com/DreamHigherCT/"
  twitter = ""
  instagram = "https://www.instagram.com/dreamhigher/"
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  body_classes = "avenir bg-white"
  featured_image = "/images/dh2.jpg"
  recent_posts_number = 2
